
name: Build and Release APK

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Build Release APK
      run: |
        cd v2
        chmod +x ./gradlew
        ./gradlew assembleRelease
        
    - name: Upload APK to Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        artifacts: "v2/app/build/outputs/apk/release/app-release.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
  