
name: Build Android APK

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Build Signed APK (avec signature debug)
      run: |
        cd v2
        chmod +x ./gradlew
        ./gradlew assembleDebug  # ⬅️ CHANGE à assembleDebug pour avoir un APK signé

    - name: Delete existing release (if any)
      uses: dev-drprasad/delete-tag-and-release@v1.0
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ github.ref_name }}

    - name: List files to debug
      run: |
        find . -name "*.apk" -type f
        ls -la v2/app/build/outputs/apk/
        ls -la v2/app/build/outputs/apk/release/

    - name: Rename APK
      run: |
        cd v2/app/build/outputs/apk/debug
        cp app-debug.apk DamesLaMaison-v${{ github.ref_name }}.apk
        
    - name: Upload APK to Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        artifacts: "v2/app/build/outputs/apk/debug/DamesLaMaison-v${{ github.ref_name }}.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
