
name: Build Debug

on: [push]

jobs:
  build-debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Build with detailed output
      run: |
        cd v2
        chmod +x ./gradlew
        ./gradlew assembleDebug --info
        ./gradlew assembleRelease --info
        
    - name: Find APK files
      run: |
        echo "=== Searching for APK files ==="
        find v2 -name "*.apk" -type f
        echo "=== Build outputs ==="
        find v2 -type d -name "outputs" | head -5
